/*
    The HelloWorld class below was generated by ChatGPT in the following
    conversation: https://chatgpt.com/share/5c2f7f6a-4131-407b-8b91-6327344a6095
*/
public class HelloWorld {
    public static void main(String[] args) {
        System.out.println("Hello, World!");
    }
}
